### ISSUE TITLE
Release 0.12

### ISSUE THREAD

**Issue by d0ugal** [mkdocs/mkdocs#442]
- [x] Update website DNS. #405 
- [x] Fix blocker #441
- [x] Verify potential blocker #439
- [x] Finalise and merge release notes #437
- [x] Bump version
- [x] Publish to PyPI

**Comment by jaredwilkening** [comment]
+1 looking forward to this

**Comment by d0ugal** [comment]
Just waiting until I have some spare time to firefight any immediate issues. Probably tomorrow morning (UTC+1)

**Comment by jaredwilkening** [comment]
Thank you sir!
